### PR TITLE
#74 - fixed styling and refactored step1 and step2 of the donation form

### LINKED ISSUE #74: dono form minor details to match figma
refine and refactor to match the figma as close as possible.

### PR DESCRIPTION
**Pull request by piersolh**
## Description

Briefly describe the changes and why they are needed.

## Changes Made

- [ ] Backend changes
- [X] Frontend changes
- [ ] Database schema changes
- [ ] Configuration updates
- [ ] Other

## Testing & Verification

- [X] Unit tests pass
- [X] Manual testing completed
- [X] No breaking changes

**Verification Steps:**
visually verified, tried different inputs to make sure step 1 and 2 still work

Old UI: [link](https://github.com/Code-4-Community/fcc/pull/68)

## New UI

Screenshot 2026-03-14 at 11 19 46 PM
Screenshot 2026-03-14 at 11 20 08 PM
Screenshot 2026-03-14 at 11 20 54 PM
Screenshot 2026-03-14 at 11 22 21 PM

## Future Improvements/Notes

- The "edit fees and tips" button doesn't work
- Credit card info box doesn't automatically format
## Related Issues

Closes #74

### CODE REVIEW

**Comment by piersolh** [comment]
I wasn't sure what the final design was for step 3/4, it wasn't clear from the figma so I wasn't sure if that was in the scope of the ticket

File: apps/frontend/src/containers/donations/steps/DonationAmount.tsx [hunk 1]
```diff
@@ -0,0 +1,95 @@
+import { cn } from '@lib/utils';
```
Comment (piersolh) [inline apps/frontend/src/containers/donations/steps/DonationAmount.tsx]: I pulled this section out from step 1 to make the code cleaner + easier to read

**Review by thaninbew — APPROVED** [review]
Looks great!

I love that you decided to also take the time to modularize things within the dono pages. 

To add some real feedback to why it was good:
- It reduces complexity in Step1/Step2 and makes UI pieces reusable/testable
- scope is contained to the donation form UI
- manually tested so i trust ya (jk i tested it too.. or did i??)
